-- ============================================
-- VEHICLE QUALITY RCA PLATFORM — DEPLOYMENT SCRIPT
-- Run this on a fresh Snowflake trial account
-- ============================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS VEHICLE_DB;
CREATE SCHEMA IF NOT EXISTS VEHICLE_DB.VEHICLE_SCHEMA;
CREATE WAREHOUSE IF NOT EXISTS cnctd_mblty_wh
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE cnctd_mblty_wh;
USE DATABASE VEHICLE_DB;
USE SCHEMA VEHICLE_SCHEMA;

-- Grants (needed for agent/semantic view creation)
GRANT CREATE AGENT ON SCHEMA VEHICLE_DB.VEHICLE_SCHEMA TO ROLE ACCOUNTADMIN;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;

-- ============================================
-- Internal stage for CSV upload
-- ============================================
CREATE OR REPLACE STAGE VEHICLE_DATA_STAGE
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

-- >>> MANUAL STEP: Upload these CSV files to @VEHICLE_DATA_STAGE before continuing:
-- vehicles_zipcodes_distances_dates_weather_dtc.csv, part_battery.csv,
-- battery_supplier.csv, dtc_battery_error_codes.csv, battery_type.csv, battery_components.csv
-- (Via Snowsight: Data > Databases > VEHICLE_DB > VEHICLE_SCHEMA > Stages > VEHICLE_DATA_STAGE > "+ Files")

-- ============================================
-- Table definitions
-- ============================================

CREATE OR REPLACE TABLE VEHICLES_ZIPCODES_DISTANCES_DATES_WEATHER_DTC (
    CAR_ID NUMBER(38,0), VIN VARCHAR, MODEL_YEAR NUMBER(38,0), VEHICLE_CONFIG VARCHAR,
    DOORS NUMBER(38,0), STATE VARCHAR, STATE_AB VARCHAR, CITY VARCHAR, COUNTRY VARCHAR,
    PART_NUMBER VARCHAR, BATTERY_SERIAL_NUMBER VARCHAR, ZIP NUMBER(38,0),
    LONGITUDE NUMBER(38,6), LATITUDE NUMBER(38,6), DES_LONG NUMBER(38,6), DEST_LAT NUMBER(38,6),
    DIST_IN_M NUMBER(38,2), RECORD_COUNTS NUMBER(38,0), DATE_VALUES DATE,
    AVG_TEMP_F NUMBER(38,1), AVG_WIND_SPEED_MPH NUMBER(38,1), TOT_PRECIPITATION_IN NUMBER(38,2),
    TOT_SNOWFALL_IN NUMBER(38,2), DTC_ERROR_CODE NUMBER(38,0)
);

CREATE OR REPLACE TABLE PART_BATTERY (
    PART_ID NUMBER(38,0), AH NUMBER(38,0), AMP_HOURS VARCHAR, TERMINAL VARCHAR,
    SIZE_LENGTH_CM NUMBER(38,0), MFG_YEAR NUMBER(38,0), PART_NUMBER VARCHAR,
    TYPE NUMBER(38,0), SUPPLIER NUMBER(38,0), TEMP_RANGE_CELSIUS VARCHAR,
    TEMP_RANGE_FAHRENHEIT VARCHAR, VOLTAGE_RANGE VARCHAR,
    RECOMMENDED_CHARGING_VOLTAGE_RANGE VARCHAR, RECOMMENDED_CHARGING_CURRENT_RANGE VARCHAR,
    OVERCHARGE_PROTECTION NUMBER(38,0), OVERCURRENT_PROTECTION NUMBER(38,0),
    DISCHARGE_CURRENT VARCHAR, CUT_OFF_VOLTAGE VARCHAR
);

CREATE OR REPLACE TABLE BATTERY_SUPPLIER (
    ID NUMBER(38,0), NAME VARCHAR, STATE VARCHAR, LATITUDE NUMBER(38,4), LONGITUDE NUMBER(38,4)
);

CREATE OR REPLACE TABLE DTC_BATTERY_ERROR_CODES (
    ERROR_ID NUMBER(38,0), ERROR_CODE VARCHAR, DESCRIPTION VARCHAR
);

CREATE OR REPLACE TABLE BATTERY_TYPE (
    ID NUMBER(38,0), NAME VARCHAR
);

CREATE OR REPLACE TABLE BATTERY_COMPONENTS (
    BATTERY_TYPE NUMBER(38,0), ANODE VARCHAR, CATHODE VARCHAR, ELECTROLYTE VARCHAR
);

-- ============================================
-- Load data from stage
-- ============================================
COPY INTO VEHICLES_ZIPCODES_DISTANCES_DATES_WEATHER_DTC FROM @VEHICLE_DATA_STAGE/vehicles_zipcodes_distances_dates_weather_dtc.csv;
COPY INTO PART_BATTERY FROM @VEHICLE_DATA_STAGE/part_battery.csv;
COPY INTO BATTERY_SUPPLIER FROM @VEHICLE_DATA_STAGE/battery_supplier.csv;
COPY INTO DTC_BATTERY_ERROR_CODES FROM @VEHICLE_DATA_STAGE/dtc_battery_error_codes.csv;
COPY INTO BATTERY_TYPE FROM @VEHICLE_DATA_STAGE/battery_type.csv;
COPY INTO BATTERY_COMPONENTS FROM @VEHICLE_DATA_STAGE/battery_components.csv;