USE DATABASE VEHICLE_DB;
USE SCHEMA VEHICLE_SCHEMA;

-- Dedup PART_BATTERY (fixes fan-out from duplicate PART_NUMBER batches)
-- and Gold Layer view — joins fact table with part, supplier, battery type/components, DTC codes
CREATE OR REPLACE VIEW VW_VEHICLE_QUALITY AS
SELECT
    f.CAR_ID, f.VIN, f.MODEL_YEAR, f.VEHICLE_CONFIG,
    f.STATE, f.CITY, f.ZIP, f.DATE_VALUES,
    f.AVG_TEMP_F, f.AVG_WIND_SPEED_MPH, f.TOT_PRECIPITATION_IN, f.TOT_SNOWFALL_IN,
    f.DIST_IN_M, f.PART_NUMBER, f.BATTERY_SERIAL_NUMBER, f.DTC_ERROR_CODE,
    dtc.ERROR_CODE AS DTC_STANDARD_CODE,
    dtc.DESCRIPTION AS DTC_DESCRIPTION,
    p.PART_MFG_YEAR, p.AH, p.VOLTAGE_RANGE, p.TEMP_RANGE_FAHRENHEIT,
    bt.NAME AS BATTERY_TYPE_NAME,
    bc.ANODE, bc.CATHODE, bc.ELECTROLYTE,
    s.ID AS SUPPLIER_ID, s.NAME AS SUPPLIER_NAME, s.STATE AS SUPPLIER_STATE
FROM VEHICLES_ZIPCODES_DISTANCES_DATES_WEATHER_DTC f
LEFT JOIN (
    SELECT PART_NUMBER, MFG_YEAR AS PART_MFG_YEAR, AH, VOLTAGE_RANGE, TEMP_RANGE_FAHRENHEIT, TYPE, SUPPLIER
    FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY PART_NUMBER ORDER BY PART_ID) AS rn
        FROM PART_BATTERY
    ) WHERE rn = 1
) p ON f.PART_NUMBER = p.PART_NUMBER
LEFT JOIN BATTERY_SUPPLIER s ON p.SUPPLIER = s.ID
LEFT JOIN BATTERY_TYPE bt ON p.TYPE = bt.ID
LEFT JOIN BATTERY_COMPONENTS bc ON p.TYPE = bc.BATTERY_TYPE
LEFT JOIN DTC_BATTERY_ERROR_CODES dtc ON f.DTC_ERROR_CODE = dtc.ERROR_ID;

-- Date spine + daily aggregated failure counts (fixes 2-digit year bug: 0022 -> 2022)
CREATE OR REPLACE TABLE DATE_SPINE AS
SELECT DATEADD(day, seq4(), '2022-01-01'::DATE) AS FULL_DATE
FROM TABLE(GENERATOR(ROWCOUNT => 59));

CREATE OR REPLACE TABLE DAILY_FAILURE_COUNTS AS
SELECT
    ds.FULL_DATE,
    COALESCE(f.FAILURE_COUNT, 0) AS FAILURE_COUNT
FROM DATE_SPINE ds
LEFT JOIN (
    SELECT DATEADD(year, 2000, DATE_VALUES) AS FIXED_DATE, COUNT(*) AS FAILURE_COUNT
    FROM VW_VEHICLE_QUALITY
    WHERE DTC_ERROR_CODE > 0
    GROUP BY DATE_VALUES
) f ON ds.FULL_DATE = f.FIXED_DATE
ORDER BY ds.FULL_DATE;