USE DATABASE VEHICLE_DB;
USE SCHEMA VEHICLE_SCHEMA;

CREATE OR REPLACE MCP SERVER VEHICLE_QUALITY_MCP_SERVER
  FROM SPECIFICATION $$
  tools:
    - title: "Vehicle Quality RCA & Forecasting Agent"
      name: "vehicle_quality_rca_agent"
      type: "CORTEX_AGENT_RUN"
      identifier: "VEHICLE_DB.VEHICLE_SCHEMA.VEHICLE_QUALITY_RCA_AGENT"
      description: "Answers vehicle battery quality questions — quality monitoring, root cause analysis across part/supplier/battery chemistry, and 30-day failure forecasting with confidence intervals."
  $$;

CREATE ROLE IF NOT EXISTS MCP_ACCESS_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE MCP_ACCESS_ROLE;
GRANT USAGE ON WAREHOUSE cnctd_mblty_wh TO ROLE MCP_ACCESS_ROLE;
GRANT USAGE ON DATABASE VEHICLE_DB TO ROLE MCP_ACCESS_ROLE;
GRANT USAGE ON SCHEMA VEHICLE_DB.VEHICLE_SCHEMA TO ROLE MCP_ACCESS_ROLE;
GRANT USAGE ON MCP SERVER VEHICLE_QUALITY_MCP_SERVER TO ROLE MCP_ACCESS_ROLE;
GRANT USAGE ON AGENT VEHICLE_QUALITY_RCA_AGENT TO ROLE MCP_ACCESS_ROLE;
GRANT SELECT ON SEMANTIC VIEW VEHICLE_QUALITY_SV TO ROLE MCP_ACCESS_ROLE;